In [1]:
import pandas as pd
import geopy.distance

/Users/dhkim/PycharmProjects/untitled/venv/lib/python3.8/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [31]:
x = pd.read_csv('/Users/dhkim/PycharmProjects/kakomap_crwal/data/2020-06-25_17_45_스타벅스dt.csv_review.csv', sep='\t')
x = x.drop(x.columns[0], axis=1)
x

,loc_name,address,num_review,link,reviews,scores,dates
0,스타벅스 연희DT점,"연희동 87-7 ,87-8",블로그리뷰 98,https://m.place.naver.com/restaurant/36462644?...,"['아주 좋아요 ~ 자주 이용하는 편이에요', '좋아요', '넓고 주차자리도 있어서...","['4', '4', '5', '4.5', '4.5', '4.5', '4', '5',...","['2020.06.02', '2020.06.02', '2020.05.22', '20..."
1,스타벅스 종암DT점,종암동 29-10,블로그리뷰 26,https://m.place.naver.com/restaurant/144745971...,"['좋아요', '좋아요 ㅎㅎ', '여긴 크고 작은 실수가 잦은데 학교랑 가까워서 오...","['5', '5', '4.5', '5', '5', '4', '5', '5', '5'...","['2020.06.10', '2020.06.10', '2020.06.10', '20..."
2,스타벅스 영등포신길DT점,신길동 252-9 253-331253-333253-334253-335253-336,블로그리뷰 144,https://m.place.naver.com/restaurant/35886658?...,"['조아요 ㅎㅎㅎ호ㅗㅗㅗ', '.', '좋아요', '좋아요', '시원하고 좋아요',...","['5', '5', '2.5', '3.5', '5', '4.5', '5', '3.5...","['2020.06.25', '2020.06.21', '2020.06.20', '20..."
3,스타벅스 구의DT점,구의동 67-36,블로그리뷰 90,https://m.place.naver.com/restaurant/36636853?...,"['좋아요', '아아 마셨어요 친절 친절', '.', '직원들이 많은 곳인데 사람마...","['4.5', '4', '4', '5', '5', '5', '5', '5', '5'...","['2020.06.24', '2020.06.20', '2020.06.20', '20..."
4,스타벅스 낙성대DT점,봉천동 1657-3,블로그리뷰 104,https://m.place.naver.com/restaurant/38412114?...,"['애플망고 시원하고 달달하고 상큼하니 맛나요~~', '드라이브쓰루 줄 정말 길어요...","['4.5', '5', '5', '5', '4.5', '5', '4', '5', '...","['2020.06.23', '2020.06.16', '2020.06.13', '20..."
5,스타벅스 공릉DT점,"공릉동 597-34 597-30, 597-31, 597-32",블로그리뷰 111,https://m.place.naver.com/restaurant/195402633...,"['친절하시고맛있습니다!', '너무더워서 시원한 아이스 아메리카노 한잔했네요', '...","['5', '4.5', '5', '3.5', '4.5', '4', '5', '5',...","['2020.06.23', '2020.06.18', '2020.06.18', '20..."
6,스타벅스 화곡DT점,화곡동 772-67,블로그리뷰 101,https://m.place.naver.com/restaurant/38667808?...,"['항상즐겨찾는곳입다 굿굿', '빵이 맛있어요 ㅎ', '좋아요', '친절해요', '...","['5', '4', '5', '5', '4.5', '5', '4', '5', '5'...","['2020.06.20', '2020.06.14', '2020.06.14', '20..."
7,스타벅스 신정DT점,신정동 981-15,블로그리뷰 82,https://m.place.naver.com/restaurant/160164364...,"['good', '', 'ㅇ', '#아메리카노 #벤티사이즈', '', '', '.'...","['5', '5', '4.5', '4', '5', '5', '5', '5', '5'...","['2020.06.23', '2020.06.15', '2020.05.22', '20..."
8,스타벅스 송파나루역DT점,송파동 59-9 송봉주유소,블로그리뷰 46,https://m.place.naver.com/restaurant/186664903...,"['좋아여', '직원분들 친절하고 좋아요', '친절합니다', '커피맛있어요', ''...","['5', '5', '4.5', '0.5', '5', '5', '2.5', '5',...","['2020.06.20', '2020.06.18', '2020.06.09', '20..."
9,스타벅스 강동구청DT점,성내동 550,블로그리뷰 27,https://m.place.naver.com/restaurant/131496945...,"['치즈케잌 맛나요~', '좋아요', '카페가 넓어서 좋아요!', '보통', '굿'...","['4', '5', '4', '5', '5', '5', '5', '4', '5', ...","['2020.06.23', '2020.06.14', '2020.06.13', '20..."
10,스타벅스 송파방이DT점,방이동 226-10,블로그리뷰 63,https://m.place.naver.com/restaurant/38531319?...,"['좋아여', 'ㅎ', '맛있어요', '쿨라임피지오는 안되요 돌체라떼는 맛있어요ㅔ'...","['3.5', '4.5', '3', '4.5', '5', '5', '5', '5',...","['2020.06.01', '2020.05.27', '2020.05.26', '20..."
11,스타벅스 방화DT점,방화동 293-4,블로그리뷰 80,https://m.place.naver.com/restaurant/196795198...,"['친절하고 커피맛 좋아요 👍👍👍', '좋아요~ 사회적 거리두기로 테이블을 많이 빼...","['5', '5', '3.5', '3', '5', '5', '3.5', '4', '...","['2020.06.11', '2020.06.07', '2020.06.07', '20..."
12,스타벅스 안양석수DT점,석수동 385-3,블로그리뷰 72,https://m.place.naver.com/restaurant/36860572?...,"['커피가 맛있어요~~^^', '감사합니다', '이 동네에는 뭐 거의 아무것도 없다...","['5', '5', '5', '4.5', '4', '5', '4', '4.5', '...","['2020.06.17', '2020.06.06', '2020.06.05', '20..."
13,스타벅스 광명소하DT점,소하동 1077,블로그리뷰 35,https://m.place.naver.com/restaurant/483736273...,"['커피가 너무 맛있어요!!!', '직원분 친철해요^^', '맛있어요~', '친절'...","['5', '5', '4', '4', '3.5', '3', '3', '5', '5'...","['2020.06.20', '2020.06.18', '2020.06.18', '20..."
14,스타벅스 고양DT점,고양동 568,블로그리뷰 65,https://m.place.naver.com/restaurant/37378981?...,"['다 좋은데, 1층에 모기가 있는 거 같아요...', '매장예쁘고 신메뉴 맛있어요...","['5', '4.5', '4', '5', '5', '5', '5', '5', '5'...","['2020.06.21', '2020.06.21', '2020.06.20', '20..."
15,스타벅스 역곡역DT점,괴안동 112-25,블로그리뷰 131,https://m.place.naver.com/restaurant/36424589?...,"['얌얌', '냠냠', '얌얌', '야미', '야미', '마시쏘용', 'JMT', ...","['5', '4.5', '4', '5', '5', '5', '5', '5', '5'...","['2020.06.23', '2020.06.21', '2020.06.19', '20..."
16,스타벅스 의정부회룡역DT점,호원동 433-1,블로그리뷰 84,https://m.place.naver.com/restaurant/515571805...,"['사람이 너무 많아서 음료나오는데 시간이 너무 오래걸리는거빼곤 괜찮아요', '#스...","['5', '4.5', '5', '4.5', '5', '4', '5', '3.5',...","['2020.06.09', '2020.06.07', '2020.06.01', '20..."
17,스타벅스 평촌역DT점,관양동 902 1필지,블로그리뷰 30,https://m.place.naver.com/restaurant/166610315...,"['굿', '좋아요', '좋아요', '주차장 2시간 차단봉이 생겼네요 점심시간대에는...","['3', '5', '3.5', '5', '5', '5', '5', '5', '5'...","['2020.06.22', '2020.06.20', '2020.06.19', '20..."
18,스타벅스 백석역DT점,백석동 1296-3 1층,블로그리뷰 72,https://m.place.naver.com/restaurant/33409115?...,"['맛있어요', '맛있어요', '조아요', '항상 애용하는 DT점~ 편리하고 좋아요...","['5', '5', '5', '5', '5', '5', '5', '5', '5', ...","['2020.06.23', '2020.06.22', '2020.06.22', '20..."
19,스타벅스 일산풍동DT점,경기 고양시 일산동 풍동 879,블로그리뷰 36,https://m.place.naver.com/restaurant/118866477...,"['쾌적하고 좋아요!!', '쾌적하고 친절해요!!', '편해요', '주차가 좀 아쉽...","['2.5', '5', '3.5', '4', '4.5', '5', '5', '5',...","['2020.06.22', '2020.06.16', '2020.06.02', '20..."
20,스타벅스 의정부예술의전당DT점,의정부동 543-6,블로그리뷰 41,https://m.place.naver.com/restaurant/138257798...,"['좋아요', '좋아요', '매장이 넓고 좋아요.', '그리 친절하진 않네요 점원들...","['5', '5', '5', '5', '5', '5', '4.5', '2', '2'...","['2020.06.17', '2020.06.13', '2020.06.13', '20..."
21,스타벅스 의정부신곡DT점,경기 의정부시 신곡동 263-17,블로그리뷰 49,https://m.place.naver.com/restaurant/104036776...,['깨끗하고 주차시설도 있고 좋은데 4시인데도 사람이 너무 많고 주차 할 곳이 없음...,"['5', '5', '5', '4', '5', '4', '4.5', '5', '5'...","['2020.06.12', '2020.06.07', '2020.06.02', '20..."
22,스타벅스 안양비산DT점,비산동 580-6,블로그리뷰 68,https://m.place.naver.com/restaurant/36960747?...,"['', '조금 더 시원했으면 좋겠어요', '직원이 완전 친절해요', '좋아요', ...","['4', '5', '4.5', '5', '4.5', '5', '5', '5', '...","['2020.06.25', '2020.06.18', '2020.06.08', '20..."
23,스타벅스 의왕청계DT점,경기 의왕시 청계동 829-4,블로그리뷰 21,https://m.place.naver.com/restaurant/130455799...,"['', '조용해요', '기존 에스프레소휘핑 프라푸치노가 더 나은 것 같아요..',...","['5', '5', '4.5', '3', '5', '5', '5', '5', '5'...","['2020.06.24', '2020.06.18', '2020.06.18', '20..."
24,스타벅스 부천중동DT점,중동 628-14,블로그리뷰 82,https://m.place.naver.com/restaurant/37553750?...,[],[],[]
25,스타벅스 의정부용현DT점,"경기 의정부시 용현동 189-3 4, 20, 21, 22(5필지)",블로그리뷰 32,https://m.place.naver.com/restaurant/116401071...,"['항상 친절해요', 'ㅇ', '좋아요..', '굿 좋아용', '더울 땐 역시 아아...","['5', '4.5', '4', '5', '4.5', '4.5', '5', '5',...","['2020.06.20', '2020.06.17', '2020.06.13', '20..."
26,스타벅스 시흥대야DT점,대야동 501-3,블로그리뷰 27,https://m.place.naver.com/restaurant/118913316...,"['좋아요^^', '', '', '맛있어요 쾌적해요', '쾌적하고 좋아요.', '좋...","['4.5', '5', '5', '4.5', '4', '4.5', '5', '5',...","['2020.06.22', '2020.06.22', '2020.06.13', '20..."
27,스타벅스 리버사이드팔당DTR점,도곡리 504-15,"블로그리뷰 1,295",https://m.place.naver.com/restaurant/197224424...,"['네', '좋아요', '자리 앉아서 먹기가 힘든 곳. 그만큼 사람도 많고 풍광이 ...","['4', '5', '5', '5', '2.5', '4', '5', '5', '4'...","['2020.06.22', '2020.06.18', '2020.06.18', '20..."
28,스타벅스 안양호계DT점,호계동 714-5,블로그리뷰 47,https://m.place.naver.com/restaurant/38511119?...,"['친절한 크루덕에맛있게먹고갑니다', '맛있어요 피치!!!!', '돌체는 언제먹어도...","['4', '4', '4', '5', '4', '4', '4', '4.5', '4....","['2020.06.22', '2020.06.22', '2020.06.14', '20..."
29,스타벅스 경인교대입구역DT점,작전동 852-30 852-31,블로그리뷰 25,https://m.place.naver.com/restaurant/146617747...,"['맛있고 친절함', '넓직해서 공부하기 좋아요', '경교', '이건 비추 ;;',...","['5', '4', '4', '5', '5', '5', '5', '5', '4', ...","['2020.06.23', '2020.06.20', '2020.06.19', '20..."
30,스타벅스 김포풍무DT점,풍무동 620-11,블로그리뷰 65,https://m.place.naver.com/restaurant/34363397?...,"['굿', '좋아료', '헤헤 쾌적해여', '좋아요~돌체라떼 맛있어요', '주차장도...","['5', '5', '5', '5', '5', '5', '4.5', '4', '5'...","['2020.06.18', '2020.06.15', '2020.06.15', '20..."
31,스타벅스 평내DT점,평내동 246-2,블로그리뷰 79,https://m.place.naver.com/restaurant/36995576?...,"['좋아요 주차장 만차인것만 빼면ㅎ', '드라이브스루~!!!', '굳', '굿', ...","['5', '4.5', '5', '4.5', '3.5', '4', '2.5', '3...","['2020.06.20', '2020.06.20', '2020.06.07', '20..."
32,스타벅스 남양주진접DT점,장현리 230-6,블로그리뷰 95,https://m.place.naver.com/restaurant/445673650...,['더위날리러 꾸역 꾸역 나와 맛난 커피한잔 ~ ^^ 더위는 핑계고 커피가 먹고싶어...,"['4', '5', '4.5', '5', '4.5', '4.5', '5', '4',...","['2020.06.20', '2020.06.14', '2020.06.13', '20..."
33,스타벅스 김포감정DT점,감정동 502-20,블로그리뷰 54,https://m.place.naver.com/restaurant/125286562...,"['쾌적하고 드라이브스루도 있어서 좋아요!', '맛있어요', '매장 분위기 좋아요~...","['4.5', '4.5', '4.5', '5', '5', '5', '5', '5',...","['2020.06.12', '2020.06.11', '2020.06.11', '20..."
34,스타벅스 양주광사DT점,광사동 342-7,블로그리뷰 35,https://m.place.naver.com/restaurant/186406136...,"['.', '드라이브쓰루 좋아유', '맛잇어요', '아이스아메리카노 주문했는데 진짜...","['5', '4', '5', '5', '4.5', '4', '4', '3.5', '...","['2020.06.22', '2020.06.17', '2020.06.11', '20..."
35,스타벅스 인천당하DT점,당하동 1092-7,블로그리뷰 111,https://m.place.naver.com/restaurant/37293532?...,[],[],[]
36,스타벅스 인천간석DT점,간석동 617-6,블로그리뷰 50,https://m.place.naver.com/restaurant/267527479...,"['오늘은꽁짜', '매장도 깔끔하고 좋아요', ',', '조아요', '역시 스벅~~...","['5', '4.5', '4', '4', '5', '4', '5', '4', '5'...","['2020.06.20', '2020.06.20', '2020.06.19', '20..."
37,스타벅스 북수원IC DT점,파장동 469-4,블로그리뷰 58,https://m.place.naver.com/restaurant/135945062...,"['조용한데 사람이 많아요~', '플랫화이트 아이스가 안되서 별 한개만 뺏어요. 직...","['5', '5', '4', '5', '5', '5', '5', '5', '5', ...","['2020.06.23', '2020.05.24', '2020.05.12', '20..."
38,스타벅스 수원연무DT점,연무동 247-16,블로그리뷰 30,https://m.place.naver.com/restaurant/160251952...,['너무너무 맛있어서 이것만 먹는데 컵에 전 사람이 먹던 초코가 안 닦여서 붙어있어...,"['3', '5', '4.5', '4.5', '4.5', '5', '4', '5',...","['2020.06.21', '2020.06.19', '2020.06.15', '20..."
39,스타벅스 양주덕정역DT점,덕정동 223-8,블로그리뷰 23,https://m.place.naver.com/restaurant/199300047...,"['커피맛집', '좋아영', '잘먹었습니다~', '친구랑 같이가는곳', '커피 짱'...","['5', '5', '4.5', '4.5', '4.5', '4.5', '5', '4...","['2020.06.21', '2020.06.17', '2020.06.15', '20..."
40,스타벅스 인천학익DT점,학익동 690-2 평산면옥,블로그리뷰 19,https://m.place.naver.com/restaurant/174933243...,"['쥬아요 ㅎㅎ', '돌ㅇ', '항상 사람들로 붐벼서 매장안에서는 마시지않아요. 드...","['5', '2.5', '4', '5', '5', '5', '5', '4.5', '...","['2020.06.15', '2020.06.15', '2020.05.26', '20..."
41,스타벅스 경기광주쌍령DT점,쌍령동 168,블로그리뷰 58,https://m.place.naver.com/restaurant/139235454...,"['넓고쾌적합니다', '아아 😘', '근처 스벅이 생겨서 참 좋아요 ^^', '좋아...","['5', '5', '4', '5', '5', '5', '5', '5', '5', ...","['2020.06.21', '2020.06.13', '2020.06.05', '20..."
42,스타벅스 용인마북DT점,마북동 502-152,블로그리뷰 103,https://m.place.naver.com/restaurant/37168904?...,"['스콘 안구워줘서 별하나..ㅎㅎ', '만족', '좋아요', '조용하고 좋아요 음악...","['5', '5', '5', '5', '5', '5', '4', '5', '5', ...","['2020.05.24', '2020.05.24', '2020.05.24', '20..."
43,스타벅스 동수원DT점,우만동 153-7 유성주유소,블로그리뷰 67,https://m.place.naver.com/restaurant/37179203?...,"['스타벅스 끊을 수 없어요 커피수혈 꼭필요혀', '넓고 좋습니다', '굿', '니...","['4', '5', '3.5', '4.5', '5', '4.5', '5', '5',...","['2020.06.13', '2020.05.29', '2020.05.28', '20..."
44,스타벅스 인천용현DT점,용현동 630-9,블로그리뷰 12,https://m.place.naver.com/restaurant/185474454...,"['', '', '매장도 넓고 친절해요', '스타벅스는 왜 이렇게 장사가 잘되는거여...","['4', '5', '4', '4.5', '4', '5', '4', '4', '5'...","['2020.06.25', '2020.06.24', '2020.06.21', '20..."
45,스타벅스 수원KBS DT점,인계동 363-5,블로그리뷰 76,https://m.place.naver.com/restaurant/117405344...,"['좋아요', '점심시간에 사람 많아서 정신 없으셨는지 머그컵에 달라고 했는데 플라...","['5', '4', '4', '4.5', '4', '4.5', '4.5', '5',...","['2020.06.23', '2020.06.17', '2020.06.16', '20..."
46,스타벅스 수원인계DT점,인계동 1019 1~2층,블로그리뷰 13,https://m.place.naver.com/restaurant/35643998?...,"['좋아요ㅎ 친절합니다ㅎ', '신메뉴 !! 망고요거트 블랜디드 너무맛있어요!! 진짜...","['3', '5', '5', '5', '5', '5', '5', '5', '5', ...","['2020.06.22', '2020.06.20', '2020.06.19', '20..."
47,스타벅스 수원세류DT점,세류동 325-1,블로그리뷰 81,https://m.place.naver.com/restaurant/184663533...,"['좋아요', '맛있음', 'JMT', '스타벅스 직원분들 진짜 친절', '스콘 맛...","['5', '5', '4.5', '5', '4.5', '4', '3', '5', '...","['2020.06.22', '2020.06.19', '2020.06.18', '20..."
48,스타벅스 수원IC DT점,영덕동 522-2 LG동광주유소,블로그리뷰 29,https://m.place.naver.com/restaurant/34015944?...,"['스타벅스는 역시 이야아아아아', '스벅은 항상 맛있어요.', '..', '위치굿...","['5', '0.5', '5', '5', '5', '3.5', '4', '3.5',...","['2020.06.14', '2020.05.30', '2020.05.30', '20..."
49,스타벅스 용인동백DT점,상하동 461-2,블로그리뷰 124,https://m.place.naver.com/restaurant/37902911?...,"['', '이번 시즌 음료 모두 맛있다!', '편한데 샌디치 종류가 없어요ㅠ', '...","['5', '5', '5', '4.5', '5', '5', '4', '5', '5'...","['2020.06.25', '2020.06.22', '2020.06.19', '20..."
50,스타벅스 수원권선DT점,오목천동 321-20,블로그리뷰 64,https://m.place.naver.com/restaurant/114460917...,"['딸아이와 데이트', '오래간만에 스벅데이트', '', '', '좋아요', '열공...","['5', '4.5', '4', '4.5', '1', '5', '4', '5', '...","['2020.06.20', '2020.06.16', '2020.06.14', '20..."
51,스타벅스 수원망포DT점,망포동 38-23 GS칼텍스삼신주유소,블로그리뷰 64,https://m.place.naver.com/restaurant/37336568?...,['다 좋은데 매장앞 주차를 못하게 되서 안타깝네요ㅡㅡ구청에 민원이 들어와서 막았다...,"['4', '5', '4.5', '5', '5', '5', '3.5', '5', '...","['2020.06.25', '2020.06.25', '2020.06.21', '20..."
52,스타벅스 동두천DT점,지행동 475-1,블로그리뷰 11,https://m.place.naver.com/restaurant/37929130?...,"['좋아요~~~', '좋아용', '방문을인정합니다', '#스타벅스', '', 'Dt...","['4.5', '4', '4.5', '5', '3.5', '5', '4', '5',...","['2020.06.15', '2020.06.13', '2020.06.08', '20..."
53,스타벅스 신영통DT점,반월동 163-3,블로그리뷰 98,https://m.place.naver.com/restaurant/37408371?...,"['더운여름에강추인메뉴에요', '친절하고 맛있는 스타벅스 바닐라라떼~', '제아지트...","['4', '5', '3', '5', '2.5', '5', '3.5', '5', '...","['2020.06.21', '2020.06.11', '2020.06.08', '20..."
54,스타벅스 화성병점DT점,진안동 873-4,블로그리뷰 61,https://m.place.naver.com/restaurant/286427666...,"['돌체라떼마싰어요', '.', '와이프랑 각자 줄서서 받은 백 받았습니다. 핑크 ...","['4', '5', '5', '5', '5', '5', '5', '5', '5', ...","['2020.06.24', '2020.06.15', '2020.06.07', '20..."
55,스타벅스 동탄능동DT점,능동 471-7,블로그리뷰 56,https://m.place.naver.com/restaurant/123447627...,"['좋습니다 깔끔해요..', '드라이브쓰루 차량들이 통행자를 막아선다.', '음료는...","['5', '4', '5', '5', '5', '5', '5', '4.5', '4'...","['2020.06.07', '2020.06.02', '2020.06.01', '20..."

In [35]:
x['reviews'][0]

"['아주 좋아요 ~ 자주 이용하는 편이에요', '좋아요', '넓고 주차자리도 있어서 좋아요', '조아요', '커피맛이 약해요', '', '음료는 너무 맛난데..사람이 너무 많아여 ㅠㅠ', '굿굿', '굿굿', '친절하고 커피맛있음', '커피2잔 샌드위치1개 주문했더니 물티슈는 1개 주네요 ㅠ', '드라이브스루때문에 한잔시켜도 좀 오래걸려요ㅜㅜ 급하신분이면 사이렌오더로 미리시키는게 좋을것같아요', '잉글리쉬머핀 헤비하지않고 맛있음. 카페위치 좋고, 매장널찍해서 편하게 이용가능함. 드라이브스루때문에 붐비는시간대 걸리면 주문음료 나오는데 시간이 좀 걸릴수있음', '시끄러움', '맛있어욤', '친절합니당~~~~~', '맛있어욤', '돌체라떼 짱~~!~!~!~!', '좋아요', '쿳', '피치레몬블랜디드 맛있어요 생복숭아가 씹혀요 굿', '쾌적하고 좋아용', '보통 스타벅스 맛', 'DT편하고좋아여', '굿', '커피맛이좋아요']"

In [37]:
x['reviews'][0] = {'temp':0, 'temp2':1}

In [38]:
x['reviews'][0]

{'temp': 0, 'temp2': 1}

In [28]:
x['receipt_num'] = x['dates'].map(lambda x:len(x))
y = x.loc[0, 'scores']
y = y.replace('[', '')
y = y.replace(']', '')
[int(k) for k in y.split(',')]

ValueError: invalid literal for int() with base 10: "'4'"

In [3]:
x = pd.read_csv('data/2020-06-25_16_23_스타벅스dt.csv', sep='\t')
x = x.drop(x.columns[0], axis=1)
x

,loc_name,address,num_review,link
0,스타벅스 연희DT점,"연희동 87-7 ,87-8",블로그리뷰 98,https://m.place.naver.com/restaurant/36462644?...
1,스타벅스 종암DT점,종암동 29-10,블로그리뷰 26,https://m.place.naver.com/restaurant/144745971...
2,카페,신길동 252-9 253-331253-333253-334253-335253-336,블로그리뷰 144,https://m.place.naver.com/restaurant/35886658?...
3,스타벅스 영등포신길DT점,구의동 67-36,블로그리뷰 90,https://m.place.naver.com/restaurant/36636853?...
4,스타벅스 구의DT점,봉천동 1657-3,블로그리뷰 104,https://m.place.naver.com/restaurant/38412114?...
...,...,...,...,...
244,스타벅스 대구칠성DT점,용담삼동 2572-4 화이트하우스,블로그리뷰 34,https://m.place.naver.com/restaurant/35720213?...
245,카페,외도일동 401-1,블로그리뷰 431,https://m.place.naver.com/restaurant/183254138...
246,스타벅스 대구두류DT점,도남동 377,블로그리뷰 503,https://m.place.naver.com/restaurant/104882012...
247,스타벅스 대구공평DT점,고성리 238,블로그리뷰 244,https://m.place.naver.com/restaurant/69594415?...
248,스타벅스 대구상인DT점,고내리 340,블로그리뷰 144,https://m.place.naver.com/restaurant/86596503?...

In [5]:
x.loc[:2,:]

,loc_name,address,num_review,link
0,스타벅스 연희DT점,"연희동 87-7 ,87-8",블로그리뷰 98,https://m.place.naver.com/restaurant/36462644?...
1,스타벅스 종암DT점,종암동 29-10,블로그리뷰 26,https://m.place.naver.com/restaurant/144745971...
2,카페,신길동 252-9 253-331253-333253-334253-335253-336,블로그리뷰 144,https://m.place.naver.com/restaurant/35886658?...

In [4]:
print(geopy.distance.vincenty(('32','53'), ('32.1','53.001')).km)

11.089170659235641

<ipython-input-4-c402b5a99461>:1: DeprecationWarning: Vincenty is deprecated and is going to be removed in geopy 2.0. Use `geopy.distance.geodesic` (or the default `geopy.distance.distance`) instead, which is more accurate and always converges.
  print(geopy.distance.vincenty(('32','53'), ('32.1','53.001')).km)

In [12]:
mac_edit = pd.read_csv('data/new2_2020-06-24_16_59_맥드라이브.csv', sep='\t')
mac_edit = mac_edit.drop('Unnamed: 0', axis=1)
mac_edit = mac_edit[['mac_name', 'latitude', 'longitude']]
mac_edit['SORT'] = '맥도날드'
mac_edit

              mac_name   latitude   longitude  SORT
0           맥도날드 양평SK점  37.530980  126.893343  맥도날드
1         맥도날드 양천구청DT점  37.515464  126.862954  맥도날드
2            맥도날드 고척DT  37.497228  126.863535  맥도날드
3           맥도날드 염창DT점  37.552891  126.870164  맥도날드
4           맥도날드 서초GS점  37.486421  127.009869  맥도날드
..                 ...        ...         ...   ...
211       맥도날드 제주시청DT점  33.481468  126.541146  맥도날드
212       맥도날드 제주공항DT점  33.495155  126.492695  맥도날드
213        맥도날드 제주일도DT  33.506433  126.538460  맥도날드
214      맥도날드 제주서귀포DT점  33.253216  126.562716  맥도날드
215  맥도날드 제주월드컵스타디움DT점  33.258433  126.435314  맥도날드

[216 rows x 4 columns]

In [5]:
loc_info = pd.read_excel('/Users/dhkim/PycharmProjects/kakomap_crwal/data/ST_MAC_DT.xlsx', sep='\t')
loc_info_mac = loc_info[loc_info.SORT == '맥도날드']
loc_info_star = loc_info[loc_info.SORT == '스타벅스']
loc_info_star = loc_info_star.reset_index().drop('index', axis=1)

In [35]:
loc_info_new = pd.concat([mac_edit, loc_info_star]).reset_index().drop('index', axis=1)
loc_info_new.to_csv('/Users/dhkim/PycharmProjects/kakomap_crwal/data/ST_MAC2_DT.csv', sep='\t')

In [17]:
loc_info_new

          mac_name   latitude   longitude  SORT
0       맥도날드 양평SK점  37.530980  126.893343  맥도날드
1     맥도날드 양천구청DT점  37.515464  126.862954  맥도날드
2        맥도날드 고척DT  37.497228  126.863535  맥도날드
3       맥도날드 염창DT점  37.552891  126.870164  맥도날드
4       맥도날드 서초GS점  37.486421  127.009869  맥도날드
..             ...        ...         ...   ...
465   스타벅스 목포터미널DT  34.810017  126.417053  스타벅스
466    스타벅스 마산회원DT  35.220657  128.574434  스타벅스
467     스타벅스 평촌역DT  37.396431  126.969419  스타벅스
468    스타벅스 시흥대야DT  37.443912  126.790755  스타벅스
469  스타벅스 수원경수인계DT  37.267928  127.027944  스타벅스

[470 rows x 4 columns]

In [22]:
loc_info_mac = loc_info_new[loc_info_new.SORT == '맥도날드']
loc_info_star = loc_info_new[loc_info_new.SORT == '스타벅스']

In [24]:
loc_info_mac

              mac_name   latitude   longitude  SORT
0           맥도날드 양평SK점  37.530980  126.893343  맥도날드
1         맥도날드 양천구청DT점  37.515464  126.862954  맥도날드
2            맥도날드 고척DT  37.497228  126.863535  맥도날드
3           맥도날드 염창DT점  37.552891  126.870164  맥도날드
4           맥도날드 서초GS점  37.486421  127.009869  맥도날드
..                 ...        ...         ...   ...
211       맥도날드 제주시청DT점  33.481468  126.541146  맥도날드
212       맥도날드 제주공항DT점  33.495155  126.492695  맥도날드
213        맥도날드 제주일도DT  33.506433  126.538460  맥도날드
214      맥도날드 제주서귀포DT점  33.253216  126.562716  맥도날드
215  맥도날드 제주월드컵스타디움DT점  33.258433  126.435314  맥도날드

[216 rows x 4 columns]

In [25]:
loc_info_star = loc_info_star.reset_index().drop('index', axis=1)
loc_info_star

          mac_name   latitude   longitude  SORT
0      스타벅스 울산신정DT  35.544170  129.324735  스타벅스
1     스타벅스 경주보문로DT  35.853218  129.268695  스타벅스
2       스타벅스 동수원DT  37.278015  127.033828  스타벅스
3       스타벅스 서귀포DT  33.249525  126.506710  스타벅스
4     스타벅스 구미금오산DT  36.122231  128.323599  스타벅스
..             ...        ...         ...   ...
249   스타벅스 목포터미널DT  34.810017  126.417053  스타벅스
250    스타벅스 마산회원DT  35.220657  128.574434  스타벅스
251     스타벅스 평촌역DT  37.396431  126.969419  스타벅스
252    스타벅스 시흥대야DT  37.443912  126.790755  스타벅스
253  스타벅스 수원경수인계DT  37.267928  127.027944  스타벅스

[254 rows x 4 columns]

In [26]:

def get_distances_with_st(mac_df, star_df):
    rows = []
    for j in range(mac_df.shape[0]):
        mac_name = mac_df.loc[j].mac_name
        coord1 = (mac_df.loc[j].latitude, mac_df.loc[j].longitude)
        for i in range(star_df.shape[0]):
            star_name = star_df.loc[i].mac_name
            coord2 = (star_df.loc[i].latitude, star_df.loc[i].longitude)
            distance = geopy.distance.vincenty(coord1, coord2).km
            row = {
                'mac_name' : mac_name,
                'star_name' : star_name,
                'distance' : distance
                }
            rows.append(row)
    return rows

In [27]:
rows = get_distances_with_st(loc_info_mac, loc_info_star)

<ipython-input-26-cd961e17d962>:9: DeprecationWarning: Vincenty is deprecated and is going to be removed in geopy 2.0. Use `geopy.distance.geodesic` (or the default `geopy.distance.distance`) instead, which is more accurate and always converges.
  distance = geopy.distance.vincenty(coord1, coord2).km

In [28]:
mac_star_distance = pd.DataFrame(rows)
mac_star_distance

                mac_name      star_name    distance
0             맥도날드 양평SK점    스타벅스 울산신정DT  309.836061
1             맥도날드 양평SK점   스타벅스 경주보문로DT  282.343907
2             맥도날드 양평SK점     스타벅스 동수원DT   30.707365
3             맥도날드 양평SK점     스타벅스 서귀포DT  476.314033
4             맥도날드 양평SK점   스타벅스 구미금오산DT  201.790501
...                  ...            ...         ...
54859  맥도날드 제주월드컵스타디움DT점   스타벅스 목포터미널DT  172.114648
54860  맥도날드 제주월드컵스타디움DT점    스타벅스 마산회원DT  293.601200
54861  맥도날드 제주월드컵스타디움DT점     스타벅스 평촌역DT  461.655898
54862  맥도날드 제주월드컵스타디움DT점    스타벅스 시흥대야DT  465.488437
54863  맥도날드 제주월드컵스타디움DT점  스타벅스 수원경수인계DT  448.089152

[54864 rows x 3 columns]

In [29]:
mac_star_distance['mac_name'].unique().shape

(216,)

In [30]:
mac_star_distance[mac_star_distance['mac_name']=='맥도날드 부산엄궁DT점']['distance'].argmin()

81

In [31]:
def find_mindist_starbucks(each_mac_df):
    new_df = {}
    each_mac_df = each_mac_df.reset_index(drop=True)
    new_df['distance'] = each_mac_df['distance'].min()
    new_df['star_name'] = each_mac_df.loc[each_mac_df['distance'].argmin()]['star_name']

    return pd.Series(new_df, index=['star_name', 'distance'])

In [32]:
mac_star_distance2 = mac_star_distance.groupby(['mac_name']).apply(find_mindist_starbucks)
mac_star_distance3 = mac_star_distance2.reset_index()

In [33]:
mac_star_distance3

         mac_name      star_name   distance
0      맥도날드 가락DT점    스타벅스 송파방이DT   1.580628
1    맥도날드 강남삼성DT점      스타벅스 구의DT   5.207358
2    맥도날드 경주보문DT점   스타벅스 경주보문로DT   0.937271
3    맥도날드 경주용강DT점   스타벅스 경주터미널DT   3.931237
4    맥도날드 경주황남DT점   스타벅스 경주터미널DT   0.160485
..            ...            ...        ...
211  맥도날드 포항장성DT점    스타벅스 포항장성DT   0.067776
212  맥도날드 하남시청DT점    스타벅스 하남미사DT   3.336015
213   맥도날드 해운대DT점  스타벅스 해운대달맞이DT   1.143940
214  맥도날드 화성봉담DT점    스타벅스 수원권선DT   2.669242
215  맥도날드 화성향남DT점    스타벅스 오산갈곶DT  13.820364

[216 rows x 3 columns]

In [34]:
mac_star_distance3.to_csv('mac_star_distance.csv', sep='\t')